### ISSUE TITLE
How to install : Ethernet controller: Qualcomm Atheros Killer E2400 Gigabit Ethernet Controller (rev 10)

### ISSUE THREAD

**Issue by ZerooCool** [vmayoral/ubuntu-vivid#1]
Hello,

Can i use this tutorial for my linux mint 20, and, install Ethernet controller: Qualcomm Atheros Killer E2400 Gigabit Ethernet Controller (rev 10) ?

This tutorial use ubuntu-vivid repo.

https://itectec.com/ubuntu/ubuntu-is-there-any-way-to-install-atheros-e2400-drivers/

**Comment by vmayoral** [comment]
Sure thing. Feel free to grab what’s useful. Just attach a reference to this source.

Cheers,
